### ISSUE TITLE
Table Generator

### ISSUE THREAD

**Issue by JJFritz** [JohnTendik/jtrt-tables#10]
Hi John,
I have a undefined index issue, I´m have installed Wordpress 4.6, pls see
![tabel generator issue](https://cloud.githubusercontent.com/assets/21372006/18160522/30a187fc-702e-11e6-8690-f5b456a830ed.JPG)

Thanks

Jürgen

**Comment by JohnTendik** [comment]
Hello Jürgen

Thanks for using my plugin and providing feedback. I'm looking at the picture and it looks like there is an issue with the way I'm using array/object selectors in line 13 of the shortcode file. 

Do you possibly have the version of PHP you're running on your server? 

On a another note, did you possibly update from a previous version of the plugin? ie 2.0? From what I can tell from the picture the issue is either the table didn't properly save to the backend or the old version of PHP. 

Is there anything else that seems to be missing/not working right? If you watch the video on the plugin page, you should get an idea of how the plugin is supposed to work.

Thanks for bringing this to my attention, I will look into it this weekend. 
John

**Comment by JJFritz** [comment]
Hello John,

 

thanks a lot for your reply J

The php Version of the Server is 5.6.25, of the Wordpress installation 5.6 CGI. The MySQL Version is 5.6.31.

I have installed this Wordpress Site completely new, so there was no other or older version of php or the plugin. In the moment it is the only plugin that doesn´t work right. I had some issues with the PDF Viewer of ThemeNcode, but this was fixed by the plugin author by uninstall iTheme Security. I checked the .htaccess and it seems as if ITheme Security didn´t leave any snipets. 

Would be great if you could help me, because JTRT Responsive tables has all features I need.

Bests

Jürgen

                                                                                                  

 

 <http://www.ipapress.i-pa.org/en/subscribe-for-the-ipa-newsletter/> Sign up for the IPA News!

 <http://www.i-pa.org/> www.i-pa.org 

                                                                                                  

 

 

Von: John Tendik [mailto:notifications@github.com] 
Gesendet: Freitag, 2. September 2016 16:51
An: JohnTendik/jtrt-tables
Cc: JJFritz; Author
Betreff: Re: [JohnTendik/jtrt-tables] Table Generator (#10)

 

Hello Jürgen

Thanks for using my plugin and providing feedback. I'm looking at the picture and it looks like there is an issue with the way I'm using array/object selectors in line 13 of the shortcode file. 

Do you possibly have the version of PHP you're running on your server? 

On a another note, did you possibly update from a previous version of the plugin? ie 2.0? From what I can tell from the picture the issue is either the table didn't properly save to the backend or the old version of PHP. 

Is there anything else that seems to be missing/not working right? If you watch the video on the plugin page, you should get an idea of how the plugin is supposed to work.

Thanks for bringing this to my attention, I will look into it this weekend. 
John

**Comment by JohnTendik** [comment]
Hey Jürgen,

I could not get this problem reproduced. However, I tried to better test for undefined indexes within the shortcode file. If you can replace the contents of shortcodegen file with the latest code found on github ![here](https://github.com/JohnTendik/jtrt-tables/blob/master/admin/partials/jtrt-responsive-tables-shortcode-gen.php) and let me know if it fixes part of the problem it would definitely help me out. 

Also, I know its a little bit late for this but what happens if you try to save the table? 

Thanks
John

**Comment by JJFritz** [comment]
Hi John,
I can give you admin access, mabe would be the easiest way?
Greetings
Jürgen

**Comment by JohnTendik** [comment]
Ok if you wish to do that, then sure but dont paste your info here on github. Email it to me privately :P

**Comment by JJFritz** [comment]
done :-)

**Comment by JohnTendik** [comment]
Hey,

I'm going to sleep now, its very late (4:30am) so I will try the fix tomorrow when I wake up. Also do you mind sending the credentials again? From what I got I didn't understand it much. Looked like it was in german :D

Thanks
John

**Comment by JJFritz** [comment]
Godd night, sleep well :-) 
My english is not so good, what are credentials? The admin access?

**Comment by JohnTendik** [comment]
Thabk you ;) Also yes, the user and pass so I can login to the WordPress dashboard.

**Comment by JohnTendik** [comment]
Hello Jürgen,

First I want to thank you for allowing me access to your admin area. It definitely helped. 

I think you may have wp-debug set to TRUE. This is normally ok for development but you shouldn't have this on during live. The notices you were seeing were not really errors. The table would have worked even if those displayed, however due to my sloppy coding- those notice warnings were appearing in the front-end with the tables :P That's no good :P I fixed it for you for now, I will include this fix for the next update so others do not run into the same thing. Let me know if this works for you. 

If you run into any more issues or have any questions please feel free to contact me. 

P.S. I created a sample table and a sample post to test things out. You can delete those since they're just tests.

Thanks
John

**Comment by JJFritz** [comment]
Hello John,

Thanks a lot – the plugin works perfect now!!!

Many thanks for your time and great support J

All the best

Jürgen

 

                                                                                                  

 

 <http://www.ipapress.i-pa.org/en/subscribe-for-the-ipa-newsletter/> Sign up for the IPA News!

 <http://www.i-pa.org/> www.i-pa.org 

                                                                                                  

 

 

Von: John Tendik [mailto:notifications@github.com] 
Gesendet: Montag, 5. September 2016 20:42
An: JohnTendik/jtrt-tables
Cc: JJFritz; Author
Betreff: Re: [JohnTendik/jtrt-tables] Table Generator (#10)

 

Hello Jürgen,

First I want to thank you for allowing me access to your admin area. It definitely helped. 

I think you may have wp-debug set to TRUE. This is normally ok for development but you shouldn't have this on during live. The notices you were seeing were not really errors. The table would have worked even if those displayed, however due to my sloppy coding- those notice warnings were appearing in the front-end with the tables :P That's no good :P I fixed it for you for now, I will include this fix for the next update so others do not run into the same thing. Let me know if this works for you. 

If you run into any more issues or have any questions please feel free to contact me. 

P.S. I created a sample table and a sample post to test things out. You can delete those since they're just tests.

Thanks
John

**Comment by JohnTendik** [comment]
No problem :P 

Thanks for using my plugin and providing feedback! 

If you run into any more issues or have questions feel free to contact me.

John
