### ISSUE TITLE
Plugin Not saving Data

### ISSUE THREAD

**Issue by IgnitionSarl** [JohnTendik/jtrt-tables#13]
Hello John 
Great Work for your table plugin 
I tried to use the plugin several times , each time i save the data and the page updates , all the inserted data disappear  , i tried to uninstall and reinstall , the same problem.
Also when i drop the code in the frontend editor i got an error "error:cannotLocateTable"
http://mounturtle.com/mountaineering-achievement/

i am using plugin v,3.0.2 and wordpress 4.6.1
Can you advise how to solve this issue please.

**Comment by JohnTendik** [comment]
Hey I'm hearing this issue come up often and for some reason I cannot reproduce this issue. I've setup 4 different environments all running different versions of wordpress and PHP. 

The number one cause of the table not saving properly is usually due to the table being a very large size. Are you importing a CSV file with a lot of rows/columns at all? 

Is there any way you can give me partial access to your backend so I can do some testing? If its a live website, then its ok I wouldn't want to mess with your site, but if you're working on a test website that you don't mind me going in and peeping through the site to see what may be causing this issue it would definitely help a lot. Not only for me, but for other users who may be running into the same problem. 

Let me know if that's a possibility and thank you for using my plugin and providing feedback.

John

**Comment by IgnitionSarl** [comment]
Dear John, 
You can have access to my website if it could help you track the error, I’m still in beta version.
It’s not a CSV problem , I’m not able to add a single row or column either 
 
http://mounturtle.com/wp-login.php
User: 	Mountadmin
Pass:	       diV34i9n7A(

ftp:
mounturtle.com
UserName: mounturtle
PassWord: ;diV34i9n7A(


Thank you in advance, appreciated

**Comment by JohnTendik** [comment]
Is there any way you can edit those details out? Its not safe to have that info for the public to see. I'll do some testing today and let you know of the results. 

Thanks
John

**Comment by IgnitionSarl** [comment]
Can u send me your private email so i could change the info and send it
On Sep 15, 2016 8:51 PM, John Tendik <notifications@github.com> wrote:Is there any way you can edit those details out? Its not safe to have that info for the public to see. I'll do some testing today and let you know of the results. 

Thanks
John

**Comment by JohnTendik** [comment]
Hey I sent you an email earlier don't know if you got it. I replied from the guthub email so I don't think it did. I can't see your email so if you want just send me an email at Johntendik@hotmail.com directly. 

Thanks 
John

**Comment by JohnTendik** [comment]
Hey,

I wasn't able to reproduce the issue at all. I created 2 test tables and tried to edit the one you created named "Achievements".

As you can see both the tables I created and your table seem to show up fine. I'm not sure exactly what's happening. Can I ask what browser you're using? At this point I have nothing to test other than browser specific issues. I was able to create the tables, please see the sample ones I created on the draft page. 

Other than a few small styling issues I'm not seeing anything out of the ordinary. 

http://mounturtle.com/?page_id=3216&preview=true

All the scripts are loading fine. I was able to save the tables as you can see. I'm not sure what to say :P 

I can try to do some more testing but im not able to reproduce the problem at all. Ill take a look at the error logs if I have access and see if theres anything in there that might give us a clue.

Thank
John

**Comment by IgnitionSarl** [comment]
Hi John, 
Sorry for all the hassle , I just realize that the problem is within firefox , and it’s a browser issue
I have attached a desktop recording showing that firefox isn’t able to save the info
I would like to thank you for your support , at least we found the bug
Thanks a lot

**Comment by JohnTendik** [comment]
Hey,

No worries, I'm just glad we were able to narrow the problem down. This gives me a great lead as to what I should be focusing on/troubleshooting. 

Thanks again for providing feedback and support!
