### ISSUE TITLE
Table width.  

### ISSUE THREAD

**Issue by TedThompson** [JohnTendik/jtrt-tables#15]
Tables are too wide on my galaxy s5 (portrait and landscape).

http://ksp.federalproductions.com/launch-log/

**Comment by JohnTendik** [comment]
Hello TedThompson, 

First thank you for using my plugin :P 

As for your issue, I noticed you didn't set any breakpoints. The plugin works by hiding certain columns when the size of the screen gets below a certain width (which you have control over). On your site you did not set any breakpoints for your table so it isn't hiding any columns which is why it looks too wide. All the columns are trying to squeeze themselves into the page and there simply isn't enough room :P 

My recommendation is to watch the tutorial video to learn about how you can set your custom breakpoints and hidden columns. I do apologize in advance for the video being incredibly boring and the lack of effort put into it but it should point you in the right direction.

Thanks again for using my plugin, if you have any more questions or comments please feel free to reopen this ticket. 

John
