### ISSUE TITLE
Filter table within shortcode

### ISSUE THREAD

**Issue by JtLively** [JohnTendik/jtrt-tables#19]
Is it possible to use a shortcode with a filter feature within it to only show specific columns or rows without having to create an entirely different table ?

**Comment by JohnTendik** [comment]
Hey JtLively, 

I'm working on an update right now, redoing the entire plugin once again. I will include this shortcode filter option for you specifically :P I realize with the current version copying/editting tables isn't very easy to work with, the UI is confusing even to me and I created the plugin :D 

Thank you for the suggestion, I will post again when the update is released, until then here is a tiny teaser :) 

![jtrttease](https://cloud.githubusercontent.com/assets/4714913/20402060/366a123a-acc9-11e6-8507-c52feaa4b870.png)

**Comment by JtLively** [comment]
Awesome. I guess I'll have to redo my tutorial video later, too.

https://youtu.be/t74Gbv-AnGY?list=PL3bVx6fO5lMCqwtFHy3V1b-p3oW3ol-pp

**Comment by JohnTendik** [comment]
:D Haha yah sorry bout that.

I love your comment at 4:50, "sadly you can't edit it[the cell] right here." which seems like a nice feature to have.. I'll have to do something about that :)

**Comment by JtLively** [comment]
For a solo project, I have no complaints whatsoever. There's always room for improvement. Also, Table Maker has quite a few highlight JS options that would be awesome. Depending on down-time, I may be able to add code for that.

Example: http://golivelively.com/2016/08/29/linux-for-the-rest-of-us-help/

**Comment by JohnTendik** [comment]
Ahh I see, the highlighting when you hover over the rows right? 

I can make that happen :) I will include row/col highlighting as a feature as well. If there is anything else you think would be a nice feature please please let me know because this is the perfect time to get them done. With this next update I'm looking to blow the competition out of the market. Move aside tablepress. :D

**Comment by JohnTendik** [comment]
Hey, would you like to beta test the update? I'm looking for people to test the update before I roll it out just in case there are some issues I didn't catch. Plus if you're interested this would be a good opportunity to get a head start on that new video :P 

Let me know if you're interested, just shoot me an email at johntendik@hotmail.com and I'll reply with the beta version of the plugin.

John

**Comment by JohnTendik** [comment]
Hey, 

Just wanted to let you know the update is out and the hover highlighting and filter is included. I had to push a hotfix to include the filter function because I forgot about it but now its there. 

[jtrt_tables id="82" filterrows="2,5,6" filtercols="1,4"]

The new shortcode attributes will filter rows or columns. It accepts a string with a number. If you have multiple columns or rows you want to filter, use commas to separate the row/col index.

So the shortcode above filterrows="2,5,6" will filter out rows 2,5, and 6. 
filtercols="1,4" will filter out columns 1 and 4. 

Those columns/rows will not show up in the front-end table. This will however effect certain styles that you've setup in the table editor. For example, cell background colors will shift up or down depending on the filtered out stuff. I will try to find a way to mitigate this effect by accounting for the filtered rows/cols but it isn't present in the current version. 

As for the previous table data, I know you had a concern about that. The plugin will detect older table data, and try to convert it ( if you see the message, click the convert my table data ). It doesn't work 100% so the breakpoints and styles from the old table will not be converted. Only the data. I know this isn't the greatest option but I'm hoping its somewhat useful. 

Oh and if you're still going to create that video tutorial, if you want I can feature it as THE tutorial video because I doubt I will come around to making one :( 

Thanks again for all the feedback and suggestions, if there's anything else you think would be a good addition to the plugin let me know and Ill do my best to include it. 

John

**Comment by JtLively** [comment]
I'll try this filter option out in a few days. Gotta wrap up some other projects.
