### ISSUE TITLE
Table not styling , and horiztonal scroll not available

### ISSUE THREAD

**Issue by cmhenry23** [JohnTendik/jtrt-tables#20]
Hi John,

Love your plugin, however, on this site, am not able to reproduce the styling I have set for the table, and the horizontal scroll bar has been removed on live site??

http://www.owneroperator.ca/provincial-regulations/

Thanks in advance for you help,

Chris

**Comment by JohnTendik** [comment]
Hi Chris, 

So I noticed your table is 8000px+ wide, its going to be hard to fit in such a large table into a small space. I re-created your table on my test site with breakpoints, here is how that would look:

http://johntestsite.byethost33.com/wp/2016/11/18/28/

As you can see, as the page gets smaller, so does the table. If this is not the behaviour you want but instead you want a scrollbar, you can add the following css code as custom css in your theme.

`pre#jtrt_short_code{overflow-x:scroll;}`
or if that doesn't work you can try this:
`div.container_inner{oveflow-x:scroll;}`
The second option may cause issues within the rest of your theme so be cautious if you were to use it. 

As for the styles, are you using example style #9? Because if so I do see it in effect, its just hard to tell when the table is flowing off the page and invisible :P 

Let me know if this helps, also be sure to look out for an update that I'm going to release soon, it will be a really good update. (trying to generate hype :D )

Thanks
John

**Comment by cmhenry23** [comment]
Thanks John!

**Comment by JohnTendik** [comment]
Hey,

I'm going to close this issue, I made this scrolling the default behaviour for the new version since I've noticed a lot of people aren't using the breakpoints for the footable script. If you have any more questions or issues please contact me and I will do my best to help out,

Thanks
John
