### ISSUE TITLE
Can you implement responsive columns for text to prevent having to scroll or bleed outside of divs/spans,etc.?

### ISSUE THREAD

**Issue by JtLively** [JohnTendik/jtrt-tables#22]
For an example, please check out http://tech4health.golivelively.com/index.php/organizations/

**Comment by JohnTendik** [comment]
Hey JtLively, 

Thanks for bringing this to my attention, it should work as you expect it but I see some abnormalities in my CSS code. Instead of width, I used max-width, also it seems the nowrap for columns in bleeding into other responsive styles. I will release a fix for this tonight, im currently at work right now so I can't do much from here.

Ill message you again when the update is out.

Thanks
John

**Comment by JtLively** [comment]
The transfer works well, by the way. I like it. Gotta find the search and filter buttons, though.

The new GUI looks great for how fast you did it.

**Comment by JohnTendik** [comment]
Awesome!  :D It was a mess trying to get the conversion to work properly so I'm glad it worked well for you :) The search and replace is located under the edit menu bar, 

unless you're talking about the filter attributes on the shortcode? [jtrt_tables id="1" filterrows="1,2,3"]

And thank you, the GUI is based off of excel so I guess since I didn't have to do design work myself this time around it looks much better :D I was on turbo mode trying to push the update out asap since the saving issue was more prevalent than ever.

**Comment by JtLively** [comment]
Nope, just the responsive thing. Thanks again.

**Comment by JohnTendik** [comment]
Hey, just got around to releasing the update now. I'm hoping the stacked responsive styles should work, please try it out and let me know if it works or if there are issues still. 

Thanks 
John

**Comment by JtLively** [comment]
Works. We'll have to work on the responsiveness of our images, but its fixed and I literally did nothing but wait. :)

**Comment by JtLively** [comment]
I'll work on another video after I learn the whole GUI.

**Comment by JohnTendik** [comment]
Sweeet! I had to release a sneak 4.0.2.1 hotfix in there because of late night coding and tiredness but I'm glad it works :D 

As for the video, like I said if you want I can feature it on the front page of the plugin directory because im not the best video creator. 

Oh and, the column hiding responsive options (breakpoint buttons) are located on the last toolbar icon dropdown menu (next to the borders icon) It should be the second from last Icon on the icon bar. It still works the same way as last time where you have to select your columns and the breakpoints that you want them hidden. This time around though, multiselect is possible so it makes it a lot easier and quicker.

Thanks again for all the support, feedback and suggestions, if there is anything else I can do or if you run into issues please contact me and I'll do my best to help out :) 

John
