### ISSUE TITLE
Search function doesn't work

### ISSUE THREAD

**Issue by JtLively** [JohnTendik/jtrt-tables#24]
Help, please. 
![github_search](https://cloud.githubusercontent.com/assets/18901899/20950444/bf0599e2-bbed-11e6-9b9f-5551b7b418cd.png)

http://tech4health.golivelively.com/index.php/organizations/

**Comment by JohnTendik** [comment]
Hey, 

The filter,search and pagination does not work with stacked columns, the reason is because when you choose stacked column responsive mode, the table turns into block elements, it is no longer a table. Its hard to get those functions to work properly with stacked columns, while I was developing I had a lot of trouble with it so I decided to take it off for release. 

I will try and look into different ways of doing filter/search for the stacked columns but for now its not available :( 

Thanks
John

**Comment by JtLively** [comment]
What is the best configuration to get the filter/search function?

**Comment by JohnTendik** [comment]
For now the best method is either using the scrolling responsive mode ( this uses the datatables filtering/sorting ) or you can use the column hiding responsive mode and which in that case the plugin will use FooTables' own filtering and sorting methods. I'd like to be able to combine them into one option but it either messes one or the other. 

John

**Comment by JohnTendik** [comment]
Hey good news, while doing bug fixes I was able to get filtering and pagination to work with stacked columns. This will be added in the new update. No sorting with stacked columns though ;(
