### ISSUE TITLE
Link disapeare when in column hiding

### ISSUE THREAD

**Issue by eschoyen** [JohnTendik/jtrt-tables#26]
When I try to change my table to column hiding everything works fine but all links dosen't work. They are only regular text unclickable.

**Comment by JohnTendik** [comment]
Hey, 

So under the same menu as the hiding columns button, there should be an option to change the column data type. If you change it from text to html the html links/images should show up. The reason it does show up if you don't change the column data type is because footables script strips out any HTML tags unless specified not to. 

Here is a picture showing you where the option is located:
![tretetete](https://cloud.githubusercontent.com/assets/4714913/21110965/3c73ef18-c054-11e6-8087-720dfe826d68.jpg)

**Comment by eschoyen** [comment]
Thank you, so much! :)
