### ISSUE TITLE
Breakpoints not being saved/displayed

### ISSUE THREAD

**Issue by instarevealed** [JohnTendik/jtrt-tables#29]
I just upgraded to the newest version of the plugin and found that the breakpoints seem to be broken.

When I'm selecting a column and applying the breakpoints, they don't seem to be printed in the HTML code within the table (on the public-facing page). Here's an example URL:
http://instarevealed.com/instagram-hashtag-sheets/

And here is a screenshot of the HTML code showing that the "th" element has an attribute of data-breakpoints="" - I'd assume it should show one of the values that I've saved in the WP dashboard.
![screen shot 2016-12-26 at 11 43 43 pm](https://cloud.githubusercontent.com/assets/24786919/21491944/d3d656d0-cbc5-11e6-92ec-5099e7a65dd8.png)

Can you please check this and let me know if you're able to replicate the issue or any suggestions on what else I can try?

Thank you! :)

**Comment by Lbischoff** [comment]
Having the same issue.  Breakpoints not setting.  Wordpress 4.6.  Removed old version of plugin and installed new one.  Recreated table and attemted to set breakpoints from the breakpoint button but it doesnt seem to hold after updating the post/table.

**Comment by JohnTendik** [comment]
Hello instarevealed,

I have checked out your site and I see what you're talking about. I can see that the breakpoints did try to save, however the values weren't passed in. I'm not sure why, I cannot seem to replicate the issue on my end. 

Right click on the table editor page and inspect the console log while you try to add breakpoints / save the table and see if you get any errors. 

Let me know if there is an error, this will hopefully push me in the right direction.

Thanks
John

**Comment by JohnTendik** [comment]
Hey Teri, 

If you could give me access so I could do some testing that would help out a lot. You can create a temp account for me and delete it when i'm done. 

Don't post the credentials here though, on my github profile my email is available, email me so its private and away from public eyes. 

Thanks
John

**Comment by JohnTendik** [comment]
Hello Teri, 

After some testing, I was able to figure out the issue, _I think._ I'm not exactly sure if this is the issue but I was able to reproduce this issue by doing the following: 

I was selecting the top header (A, B, C) as demonstrated in the following picture: 
![issue1](https://cloud.githubusercontent.com/assets/4714913/21780863/f66ef3c2-d661-11e6-9ff9-ec77a4cec9ab.jpg)


Can you try selecting the first row ( header ) value instead of selecting the entire column like so:
![issue2](https://cloud.githubusercontent.com/assets/4714913/21780891/1232a16c-d662-11e6-887a-2896d2aa559f.jpg)

I will definitely include a fix for this but in the meantime can you please confirm that this is the problem and not something else? 

Thank you for the support and feedback!
John

**Comment by instarevealed** [comment]
Hi John

Yes - clicking on Row 1 (Header) works and the changes are saved.

Thank you so much for your follow up and helping me resolve this. The table
is up and working on the site.

Teri

**Comment by JohnTendik** [comment]
Hey Teri, 

Perfect :) I will include a fix for this in the update, if you run into any more issues or have any questions feel free to contact me. 

Thanks
John
