### ISSUE TITLE
Cannot change cell border color

### ISSUE THREAD

**Issue by richardbb65** [JohnTendik/jtrt-tables#32]
Hi John—thanks for creating this plugin. I am having an issue where I want to change the color of some cell borders (actually to look like a row is combined) but trying to change the border style causes the plugin to "calculate..." indefinitely. Any ideas on how to fix or get around this issue? Thanks!

**Comment by JohnTendik** [comment]
Hi Richard, 

I have fixed this in the latest release however I haven't gotten around to releasing it to the public yet because there were still some big issues with the update. I'm going to split the update into a bug fix and then hopefully do another update later with added features. 

In the meantime, can you try this method and see if it works?

1. Right click on a cell and select a border option from the context menu
2. (nothing should show up, border wont show up but if you right click on the cell again it there will be a checkmark)
3. Save the table
4. Try the borders option now

Let me know if this works, if not I will send you the fix for the issue which you can upload and use. 

I will try to release the bug fix update asap.

As for cell border _colors_ that's actually not a feature _yet_. Its in my planned features list but currently the only way to change cell border colors would be to target cells with css.

Thanks
John

**Comment by JohnTendik** [comment]
Closing this since the new version should have fixed this problem. If you still experience the hanging when applying borders please feel free to reopen the ticket and ill take another look at it.
