### ISSUE TITLE
Unable to Change Column Sizes; Vertical Alignment Not Working

### ISSUE THREAD

**Issue by ablewebs** [JohnTendik/jtrt-tables#41]
Hi, John,

I presume the little icon that looks like 2 columns changes the width of the columns. It seems unpredictable when/if the orange buttons show up. Regardless, no matter what I have tried, choosing different sizes doesn't affect the column sizes. **I can provide you with access if required.**

Also, I have tried and tried to align the cell contents to the top of the cell and even though that option is checked, the contents are vertically centered.

I have a few tables to do that need to be responsive. And I am trying to get them implemented for my client by next week!

Thank you for any help you can give me! 

Andrea

**Comment by JohnTendik** [comment]
Hello Andrea, 

Unfortunately there is no way to specify the column size with the editor at this time, the reason being is it causes an issue with responsiveness. 

The icon you're referring to is in fact the Responsive Column hiding setting. If you select your responsive type to be "column hiding" then, this button will select which columns to hide at what sizes. 

I know its a bit confusing without a video, I have recorded like 3-4 times, but every single time the tutorial runs for too long 20+ min because of all the different feature Im trying to show. I will try my best to get a video tutorial out so all the buttons make more sense. 

As for the cell alignment, that must be a bug because it should be aligned to the setting you chose. I will take a closer look at this and If I can reproduce the issue I will get back to you with a fix. Thank you for bringing this to my attention :) 

You can always override theme settings with css if you're comfortable with editing stylesheets and adding custom styles. An example would me `#jtrt_table_82 tbody tr td { vertical-align:top!important; }` change #jtrt_table_82 to your actual table ID 

Thanks
John

**Comment by ablewebs** [comment]
Hi, John,

Thank you for your response. I definitely need the columns to be re-sizable because one column contains a large paragraph of text. I am using WP Beaver Builder and I was able to use their "tab" feature to create a tabbed version of that table since there were only four rows. It worked nicely. I used a different feature (pricing "table") in WP Beaver Builder which worked great for a couple of tables with equal width columns. So I'm okay for now. But I would really like to be able to use your solution for upcoming projects. Vertical alignment needs to be working, though.
