### ISSUE TITLE
Links disappear on Divi theme

### ISSUE THREAD

**Issue by jbakervictor** [JohnTendik/jtrt-tables#42]
I can't seem to get the html links to function when the table is displayed on a Divi theme. One table that is displaying them is between two tables that are not. Not sure what I missing.

**Comment by JohnTendik** [comment]
Hey, I'm currently on vacation, I have no access to a computer other than my phone but I will try to help you out. 

Are you by any chance using column hiding responsive option?

If so, you need to set the column data type to HTML otherwise on the frontend upon initialization the script will strip any tags.

If not, I'm going to need a bit more info. Can you either send me a link to your site, I'll check out If there are any issues or errors causing an issue. Or you can check the console tab and see if there is anything in there and link it here. 

Thanks,
John

**Comment by jbakervictor** [comment]
Wow, you zeroed right in on that. Immediately fixed when changed to classic scroller. I will test setting the column data type. 

Thanks!

**Comment by JohnTendik** [comment]
Hey no problem glad I could help :) let me know if you run into any other issues!

Thanks
John
