### ISSUE TITLE
Error in Chrome

### ISSUE THREAD

**Issue by caifasf** [JohnTendik/jtrt-tables#43]
Hi,

In chrome for PC the search engine and pagination do not work.

I test in Google Chrome Version: 57.0.2987.133 & 58.0.3029.81
and Opera Version: 43.0.2442.1144 & 44.0.2510.1449

Regards

**Comment by JohnTendik** [comment]
Hey, I'm currently on vacation and I don't have access to a computer other than my phone but I will try to help you out. 

Do you have an example/link I can see? Or if you can get me the error log from the console, it will also suffice. 

Thanks
John

**Comment by caifasf** [comment]
Hi,
Sorry my error, was problem with the Minification JS of my cache plugin.
Regards

**Comment by JohnTendik** [comment]
Hey, 

I'm glad to hear you solved the issue :) sorry I couldn't be more involved in helping solve the issue. I will keep this in mind however because I feel it may help other users in solving weird issues, I haven't done testing with minification plugins so I will definitely add this to my to do list and hopefully for future users I can provide a better experience. 

Thanks for using my plugin, if you have any questions or issues feel free to contact me I will do my best to help out. 

John
