### ISSUE TITLE
Can't insert URL link??

### ISSUE THREAD

**Issue by Will42vv** [JohnTendik/jtrt-tables#44]
I can't seem to insert the URL link into tables. Is anyone else experiencing same issue?  If this is an issue, could you please solve it? Very much needed feature!

**Comment by JohnTendik** [comment]
Hey, I'm currently on vacation, I have no access to a computer other than my phone but I will try to help you out.

Are you by any chance using column hiding responsive option?

If so, you need to set the column data type to HTML otherwise on the frontend upon initialization the script will strip any tags.

If not, I'm going to need a bit more info. Can you either send me a link to your site, I'll check out If there are any issues or errors causing an issue. Or you can check the console tab and see if there is anything in there and link it here.

Thanks,
John

**Comment by JohnTendik** [comment]
Also, are you using the insert link button or are you manually adding HTML link such as `<a href=""...` ? If youre using the button and there is an error, please provide the console error log and I will check and see if there is an issue there.

Thanks
John

**Comment by Will42vv** [comment]
Thanks for reply. 

I am using Column Hiding responsive option, indeed. How do I 'set the column data type to HTML'? 

Too, was using Insert Link button.

It seems that link is working in a backend, but not frontend. Images attached.

If you still need me to provide with console error code, can you please guide how, and where send it to.

Great plugin, by the way. One of the best I found, so far (and I was looking for a long time...) Simple, yet does everything it's suppose to. Great job.


![1-link](https://cloud.githubusercontent.com/assets/28302551/26116434/cba3355e-3a6b-11e7-971b-cc251ae75104.png)
![2-website](https://cloud.githubusercontent.com/assets/28302551/26116433/cba2b142-3a6b-11e7-9961-a0da03e25d01.png)

**Comment by JohnTendik** [comment]
Hi Will42vv, 

![](https://ibb.co/mo7EY5)

Use the highlighted button to set your column type to HTML, by default it is set to text. If you set it to HTML data type, you will see your images and links appear in the front end. 

1. Click on the column with links/HTML
2. Click on the highlighted button that looks like a table cut in two
3. Select data type HTML
4. Save & preview. 

Hope this helps :) let me know if you run into anymore issues or have any questions and thank you for using my plugin, I am glad you found it useful :) 

Thanks
John

**Comment by JohnTendik** [comment]
![](https://preview.ibb.co/nMiot5/IMG_20170517_100043.jpg)
