### ISSUE TITLE
How to Add Footable Toggle to JTRT Table

### ISSUE THREAD

**Issue by Igotthis22** [JohnTendik/jtrt-tables#45]
I have a table setup with JTRT and am hoping to hide the content initially to one row yet allow it to be expandable with a toggle as one of the cells contains a bunch of data I do not want shown initially. I found Footable as recommended by JTRT, however, between reading tutorials on their website and yours, I cannot piece together how to add in this functionality to the JTRT table. 

http://fooplugins.github.io/FooTable/docs/examples/basic/row-toggle.html

Can anyone help, please?

**Comment by JohnTendik** [comment]
Hey, I'm currently on vacation, I have no access to a computer other than my phone but I will try to help you out.

To turn on footable functionality, click on the 'table options' button above the table editor, it will lead you to the options sections for your table. Then on the options section click on 'responsive options' and select 'column hiding'. This option will load in footable and allow your table to hide columns on small screens. 

After, you have to select which columns you want to hide. You can do that by going back to the table editor, selecting the columns you want to hide and then clicking on the button that looks like a table split in two. Its so hard to explain in text I wish I could draw pictures but I'm currently on my phone.

I'm going to try and get pictures for you but for now hopefully this is enough information to get you on the right track. 

Thanks
John

**Comment by JohnTendik** [comment]
Its not the best picture, I drew it on my phone :) but hopefully this will help a little bit in identifying the buttons 

https://ibb.co/n1v9RQ

**Comment by Igotthis22** [comment]
Thanks for the fast response and while traveling. I really appreciate it!

So I turned on the column hiding in the table options. But I still cannot get the plus sign to show to expand it. 

Also, my gosh, this is so NOT user friendly at all. I cannot figure out how to get the settings right or to reset any of it to original settings to start over. I can't even get the cell to collapse and half of my columns don't even display.

https://www.screencast.com/t/FGIdpS1Udr

and the table on the back-end: https://www.screencast.com/t/u1LFZ1kG7t

Thanks for any further help you can provide!

**Comment by JohnTendik** [comment]
Hmm this is odd.

First, in the back end, does the table get stuck at "calculating" screen? If so, can you get me the console log and post it here? 

Because you are using footables, you have to set the specific columns you want HTML to appear in to data type "HTML". Click on a column and in the same settings area where you hide columns, under it there is a column type setting. (Can be seen in the second picture you posted) Try changing the data type for the first and second columns to HTML data type and let me know if you see any changes in the frontend. 

As for some of your columns not appearing that's really odd, can you link me to an example page? I'll see if there are any errors causing problems. 


As for the not user friendly comment, I appreciate your input, although its getting better I realise its not the best. I developed this plugin in my free time and work on it when I get the chance. I'm not very creative so my UX usually ends up really bad. You should have seen the first 3 revisions :) haha. However, If you have suggestions on how I can improve the UX I'm happy to hear you out. 

Thanks
John

**Comment by Igotthis22** [comment]
Thanks John.

So HTML helped with the formatting. Good call there.

Now I am stuck with adding the "+" sign in the first column (per
https://fooplugins.github.io/FooTable/docs/examples/basic/row-toggle.html) in
order to signify to expand each row and just have one row per category (if
that makes sense) show up in the table initially. I can't see a way to edit
the actual table source code in your table editor.

Here is the example table if it helps:

thesocialmediaposse (dot) com/hashtag-table-testing/

Thanks!

**Comment by JohnTendik** [comment]
Hey sorry, 

I'm currently travelling. All I have with me is my phone so I can't really do much for you at this time I just wanted to let you know. I won't be available for a month, I'll try to get to a computer but its going to be hard, I'll have to sidetrack from my plans. On the 14th I'll be staying at a hotel, I'm hoping I can snag a laptop or a computer from someone for a bit and I'll check your site/table to see if there are any errors. I can't do much from my phone. 

I did notice however when I tried to view the table of my phone, the columns were not hiding. Did you set any breakpoints for any of the columns, so they would hide? 

Thanks 
John

**Comment by Igotthis22** [comment]
Hi John,

Just wondering if you're back from traveling and if so, I would love it if
you could help me figure this out! Thanks so much!

**Comment by JohnTendik** [comment]
Hey

Unfortunately im still on vacation, however İ checked again and ıt seems you stıll have not setup breakpoınts for your table. None of the columns are hıdıng because there are no breakpoınts therefor the + sıgn ıs not appearıng. 

the way to hide columns is on the table editor, the second last button on the bottom row (beside print icon), the button icon looks like a table with 2 columns. Similar to other versions, select the column(s) you want hidden, click on the button and select the break points you want the columns to hide at.

Can you please confırm that at least 1 column has a breakpoınt? I know that on one of the pıctures you sent me there ıs a breakpoınt selected for one of the columns. If you can confırm that there ıs a breakpoınt set then you wıll eıther have to get me a copy of the console error log or allow me access to your websıte so ı can take a look at whats goıng on. If there ıs a breakpoınt set then I suspect somethıng may be happenıng ın the backend. 

Please note thıs ıs a publıc forum so do not ınclude any credentıals here. If you would allow me access to your backend create a new user for me and then emaıl me the detaıls at: 

JohnTendik@hotmail.com

Even though ım on vacatıon ı wıll do my best to help out. Let me know ıf there ıs actually a breakpoınt and we wıll go from there.

Thank you
John
