### ISSUE TITLE
Commas cause errors

### ISSUE THREAD

**Issue by MowgliB** [JohnTendik/jtrt-tables#5]
If this was a line within the CSV:

`"Cupping Notes","Rich chocolate, fruit and nuts, toffee. A solid dependable Colombian from the Huila growing region. Cocoa and Malt aroma"`

It would throw an error saying that there were too many columns in this row.

**Comment by mythirdeye** [comment]
Hi MowgliB,

Can you send me a copy of you CSV file? I will do some testing and try and figure out if I can find a fix for it. I think this is probably caused by the csvtohtml Jquery script, sometimes if the column headers or data is too long it will give off the "too many in this row" message. 

Thanks for trying out my plugin! 
John

**Comment by mythirdeye** [comment]
Opps I didn't mean to lock this.
