### ISSUE TITLE
Column hiding strips links and other HTML tags

### ISSUE THREAD

**Issue by davejtoews** [JohnTendik/jtrt-tables#53]
When I switch a table to column hiding my links disappear. It also seems to remove other HTML tags such as `<span>` or inline SVGs.

**Comment by JohnTendik** [comment]
Hey, for column hiding, you have to also change the column type for your columns. The way to do this is similar to hiding columns, the same button to add breakpoints for columns there is a secondary option to change column type. By default it is set to text, change it to HTML so that your HTML tags do not get removed on the frontend. 

Sorry for the late response I'm on vacation with limited time and internet so I just saw this now. Let me know if this helps if not I'll provide more details. 

Thanks
John

**Comment by JohnTendik** [comment]
https://github.com/JohnTendik/jtrt-tables/issues/21

**Comment by JohnTendik** [comment]
https://github.com/JohnTendik/jtrt-tables/issues/6
