### ISSUE TITLE
Access rights

### ISSUE THREAD

**Issue by han-alink** [JohnTendik/jtrt-tables#61]
Hi,
Great plugin; thanks.
Is there a way to control write access to a table for a user?
Thanks, 
Han

**Comment by JohnTendik** [comment]
Hello Han,

Unfortunately, no that is not a feature of this plugin currently. 

Although, you are more than welcome to add it as a feature to this plugin if you wish. Everything is open source. I'm working on a commented version of the javascript / php files so it is easier for developers to take over the project since I haven't been very active. 

Thanks
John
