### ISSUE TITLE
Sorting Columns doesn't work

### ISSUE THREAD

**Issue by PhysioMartin** [JohnTendik/jtrt-tables#65]
Hi John,
I created a table and everything worked well so far. Also I can sort my columns in the backend, it is working perfectly. But I (or the user) can't sort the columns in the frontend. 
I have got a very simple table with only 2 columns. The first one is text the second one numbers. Here is my page: [http://physiocongress.de/bundeskongress/ausstellerverzeichnis-test/](http://physiocongress.de/bundeskongress/ausstellerverzeichnis-test/)
Clicking on the headers won't do anything. I already saw some previous posts about this topic. Changing the column type to HTML or numbers (the second one) doesn't help either.
I'm very looking forward to your response.

**Comment by JohnTendik** [comment]
Hey, 

Sorry you're running into this issue. It seems you're using the datatables option which is throwing an error. :( 

Unfortunately I do not have time to debug or troubleshoot anything related to this plugin, my suggestion for now would be to use a separate responsive option. 

I'm currently on the lookout for someone to take over this project and continue maintaining it since a lot of people do like the plugin and are still using it. 

Thanks

JT

**Comment by jodylecompte** [comment]
Hello @PhysioMartin,

It looks like a fix for this was found but has not been integrated back into the main codebase yet. I will be creating a PR for this but in the mean time, you can follow the directions found on #34 to resolve this issue.

**Comment by JohnTendik** [comment]
Closing since @jodylecompte provided a solution and a fix. I will update the plugin in the WP svn directory tonight so everyone can have the fix =)

**Comment by PhysioMartin** [comment]
Thank your very much for your response, everything is working now :)
