### ISSUE TITLE
Error on adding csv & also html not saving

### ISSUE THREAD

**Issue by garyjhills** [JohnTendik/jtrt-tables#7]
Hi John,

Here is the csv and a screenshot of the error. Also, when I try to adjust hte table html to, say, make the price bold or hte first items in a table row bold, it doesn;t save the chanegs to teh html code.

[AFF.zip](https://github.com/mythirdeye/jtrt-tables/files/132386/AFF.zip)

**Comment by mythirdeye** [comment]
Hi Gary, 

Figured out why you're getting the column count error. The error says something about line 31 having more columns than table headers, but the error message is lying to you :D 

The actual error happens on line 32, the very last row of information. You have a value for "$2,600" so the issue arises because of the comma separator for the currency. CSV files are comma separated values so if you have an extra comma in your table, the CSV converter will assume the comma is a separator for values, which in your case is not true. So this causes the plugin to think you have 3 columns on the last row of your table, the first column being the title the second column being $2 and the third column being 600. 

I have fixed the issue simply by removing the currency format on the price column of the last row. The $2,600 now shows up as 2600 which is probably not what you want but you can freely style your cell yourself by adding the $sign before it if you want, i just didn't go into detail. Just don't add the thousands comma :D 
![gary test](https://cloud.githubusercontent.com/assets/4714913/13078100/0790eea0-d48b-11e5-8e01-99efbd32da75.jpg)


Here is the altered CSV file for you to test. 
[AFF2.zip](https://github.com/mythirdeye/jtrt-tables/files/132591/AFF2.zip)


Thanks for using my plugin and providing feedback! If you run into anymore issues please feel free to contact me :) 

John

**Comment by garyjhills** [comment]
Gah! I never even saw that when I copied the text over from my clients email!! Damn I should have caught that. Sorry to have wasted your time John. I feel like such a knob lol

**Comment by garyjhills** [comment]
I did just come across one other thing. when i go into look at the html, I make a change but there doesn't seem to be anyway to save changes if I make them to it. I change something. Click close and the change is not saved of course.

**Comment by mythirdeye** [comment]
Hi Gary, 

Np at all :) 

To edit the html for individual cells, simply double click on the cells and it will allow you to imput a new value for the table cell. 

Currently you cant edit the html by using the "vuew html" button, that will simply show you the html that makes up the table, if you change anything in that dialog box it wont save. 

However, this is probably a great feature to add. 

p.s to do edits to the table aside from the individual table cells, you will need to use developer tools, i have a gif/movie tutorial that shows how to achieve this in one of the other issue pages. im currently outside so i cant dig into at the moment. 

If you need anything else or run into more issues, please feel free to let me know :) 

thanks
John

**Comment by garyjhills** [comment]
Hi John,

Awesome that works great. Gone through and changed the items I wanted bold in the cells and all working brilliantly.

Thanks so much for all your help :) awesome plugin :D

**Comment by JohnTendik** [comment]
Hey I'm closing this issue due to the new update. Most of the CSV related issues should be solved as I started using a more enhanced converter. If you have any issues regarding the newer version of the plugin please let me know. 

John
