### ISSUE TITLE
Scroll bar at the bottom of every table since new update on Classic Scrollbar

### ISSUE THREAD

**Issue by Seamate** [JohnTendik/jtrt-tables#74]
Hello JohnTendick,
Thanks for your great plugin.
I noticed scrollbars at the bottom of all my tables after I updated to the latest version of your plugin. Before the update, the scroll bars only showed up on smaller screen widths when the table is too wide for the screen. This problem only appears on the Classic Scrollbar responsive option, and unfortunately, it is the only option that works best for the project I'm working on. 
Thanks for your anticipated response.
Please find below an image showing the issue.
![image](https://user-images.githubusercontent.com/35474522/36075877-e1ae1ba2-0f54-11e8-8fd6-09d524c48bb2.png)

**Comment by JohnTendik** [comment]
This is odd because I specifically fixed this with the latest update. Hmm interesting, maybe theme styles are overriding my auto style. Do you have the ability to edit the plugin files? If so you can open up the public css and locate the following line and add !important after the `auto`

.jtrespo-scroll{
     overflow-x: auto;
 } 

.jtrespo-scroll{
     overflow-x: auto !important;
 }

I will take another look at this however =)

Thank
JT

**Comment by Seamate** [comment]
Yes, I have access to the plugin files. I will try your suggested fix. 
Thanks a lot for the prompt reply.
Great work bro

**Comment by Seamate** [comment]
That was the Midas Touch bro! Perfect. 
![image](https://user-images.githubusercontent.com/35474522/36076522-6f4ebbe4-0f5d-11e8-8540-5207576d3e75.png)
Please, how can I ensure the edit doesn't get overidden in the next update? One more thing bro. How can I make the padding around the text in the table cells wider? The table borders are too close to the text. Again, this only appears in the Classic Scrollbar option. Tables look perfect on the other options.
Thanks for the support bro

**Comment by JohnTendik** [comment]
@Seamate Nice, glad that fixed it. I will include the code changes to this repo so the next update will include this "fix" in it so no need to worry about it being overridden on the next update :) 

You can add styles in that same public css file to update your column sizes. Normally the default scroller option will have padding around it (since its using data tables script for initialization) however it looks like your theme is removing the table styles. It probably has a special theme specific class that you need to apply to your table for it to look pretty however you can update the styles like I said in that same public css file 

for example something like this: 

.jtrespo-scroll table tbody td {
  padding: 8px;
}

Hope this helps. Im closing this ticket for now let me know if you have any other issues or comments.

**Comment by Seamate** [comment]
I have the perfect table now, thanks to your fix, and the warm, swift response. I don't have any other issues at the moment. Hoping to see more exciting features for the plugin in future releases. Thank you, thank you. You rock bro!
