### ISSUE TITLE
Manual entry of formulae into each cell

### ISSUE THREAD

**Issue by Adel000** [JohnTendik/jtrt-tables#83]
Hallo John :)

I've just downloaded your plugin. Evaluating a few table plugins.

Is there a way to make a formula applicable to a column?
If I copy the formula down, it does not update the referenced rows, so the calculated value remains the same as the copied cell.

Unfortunately, manually entering formulas for each individual cell is only feasible in tiny data sets. :(

Thanks for your help!
Adel

**Comment by JohnTendik** [comment]
Hey, @Adel000 

This is a good suggestion, the current behavior will only copy the results from the formula. I will take a look into whether this is possible or not because the current handsontable used in this project is an outdated version (newer version does not support formulas unless you pay) 

Thank you for the suggestion, I will poke you if I can make this a possibility :) 

JT
